---
receivers:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:

  otlp:
    protocols:
      http:
        endpoint: localhost.localdomain:8318

  otlp/tls:
    protocols:
      http:
        endpoint: localhost.localdomain:8443
        tls:
          cert_file: "tls/server.crt"
          key_file: "tls/server.key"
          ca_file: "tls/rootCA.crt"

exporters:
  otlphttp:
    endpoint: https://localhost.localdomain:4318
    tls:
      cert_file: "tls/client.crt"
      key_file: "tls/client.key"
      ca_file: "tls/rootCA.crt"
    # compression: none
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [otlphttp]
    metrics/plot:
      receivers: [otlp, otlp/tls]
      exporters: [debug]
    logs/plot:
      receivers: [otlp, otlp/tls]
      exporters: [debug]
    traces/plot:
      receivers: [otlp, otlp/tls]
      exporters: [debug]
  telemetry:
    logs:
      level: "debug"
